Adding ARM64 image support.  Adding image post-build smoke tests.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -18,6 +18,12 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
 
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 #v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb #v3
+
       - name: Login to Azure - PROD Subscription
         uses: Azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
         with:
@@ -54,6 +60,52 @@ jobs:
         with:
           context: src/sm-operator
           file: src/sm-operator/Dockerfile
-          platforms: linux/amd64
+          platforms: linux/amd64,linux/arm64
           push: true
           tags: ${{ steps.image-name.outputs.name }}
+
+      - name: Create kind cluster
+        uses: helm/kind-action@99576bfa6ddf9a8e612d83b513da5a75875caced # v1.9.0
+
+      - name: Smoke Test Image
+        id: smoke-test
+        env:
+          IMAGE: ${{ steps.image-name.outputs.name }}
+        run: |
+          cd src/sm-operator
+          make deploy IMG=$IMAGE
+
+          #Setup image pull secret (Until repo is made public)
+          kubectl create secret -n sm-operator-system docker-registry ghcr-login-secret --docker-server=ghcr.io --docker-username=bitwarden-devops-bot --docker-password=${{ secrets.GITHUB_TOKEN }} --docker-email=106330231+bitwarden-devops-bot@users.noreply.github.com
+
+          kubectl patch deployment sm-operator-controller-manager -n sm-operator-system --patch-file "$GITHUB_WORKSPACE/.github/workflows/test_files/deployment-patch.yaml"
+
+          count=0
+          while [[ $(kubectl get pods -n sm-operator-system -l control-plane=controller-manager -o jsonpath="{.items[*].status.containerStatuses[*].ready}") != "true" ]]; do
+            sleep 1;
+            count=$count+1
+            if [[ count -ge 30 ]]; then
+              break
+            fi
+          done
+
+          #For review purposes
+          echo "*****DEPLOYMENTS*****"
+          kubectl get deployments -n sm-operator-system
+
+          echo "*****PODS*****"
+          pods=$(kubectl get pods -n sm-operator-system -l control-plane=controller-manager | grep 2/2)
+          echo $pods
+
+          if [[ -z "$pods" ]]; then
+            echo "::error::No pods found."
+            exit 1
+          fi
+
+          echo "*****OPERATOR OK*****"
+
+      - name: Clean-up
+        run: |
+          cd src/sm-operator
+          make undeploy
+          kind delete cluster
