[BRE-1137] Removing environment and adding validation

diff --git a/.github/workflows/bump-version.yml b/.github/workflows/bump-version.yml
--- a/.github/workflows/bump-version.yml
+++ b/.github/workflows/bump-version.yml
@@ -11,13 +11,21 @@ jobs:
   bump_version:
     name: Bump version
     runs-on: ubuntu-22.04
-    environment: Production
     permissions:
       contents: write
       pull-requests: write
       id-token: write
+    env:
+      _VERSION_NUMBER: ${{ github.event.inputs.version_number }}
 
     steps:
+      - name: Validate version format
+        run: |
+          if ! [[ "$_VERSION_NUMBER" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Version number ($_VERSION_NUMBER) is not in semantic version format (X.Y.Z)"
+            exit 1
+          fi
+
       - name: Check out repo
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
 
